version: '3.8'

services:
  # 🗄️ PostgreSQL - Base de datos principal
  db:
    image: postgres:15-alpine
    container_name: clinicaperu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: skivadev
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clinica-peru-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - clinicaperu-network

  # ⚡ Redis - Para cache o BullMQ
  redis:
    image: redis:7-alpine
    container_name: clinicaperu-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - clinicaperu-network

  # 💌 MailHog - Captura de correos en desarrollo
  mailhog:
    image: mailhog/mailhog:latest
    container_name: clinicaperu-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Interfaz web (http://localhost:8025)
    networks:
      - clinicaperu-network

  # 🧭 Redis Commander - UI visual para Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: clinicaperu-redis-ui
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081" # http://localhost:8081
    depends_on:
      - redis
    networks:
      - clinicaperu-network

  # 🧰 pgAdmin - UI para administrar PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: clinicaperu-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80" # http://localhost:8082
    depends_on:
      - db
    networks:
      - clinicaperu-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  clinicaperu-network:
    driver: bridge
